version: '3.2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "asd*@&90vp8093pQ76328q19voer324bi"
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "asd*@&90vp8093pQ76328q19voer324bi"
    depends_on:
      - db
    entrypoint: sh -c "dos2unix run.sh && chmod +x run.sh && ./run.sh"
