version: '3'
services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: database_name
      PGPORT: 5432
      PGHOST: db
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - backend
    entrypoint: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend: